/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WithSearchParamsIndexRouteImport } from './routes/with-search-params/index'
import { Route as PetsIndexRouteImport } from './routes/pets/index'
import { Route as WithParamsIdRouteImport } from './routes/with-params/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WithSearchParamsIndexRoute = WithSearchParamsIndexRouteImport.update({
  id: '/with-search-params/',
  path: '/with-search-params/',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsIndexRoute = PetsIndexRouteImport.update({
  id: '/pets/',
  path: '/pets/',
  getParentRoute: () => rootRouteImport,
} as any)
const WithParamsIdRoute = WithParamsIdRouteImport.update({
  id: '/with-params/$id',
  path: '/with-params/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/with-params/$id': typeof WithParamsIdRoute
  '/pets': typeof PetsIndexRoute
  '/with-search-params': typeof WithSearchParamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/with-params/$id': typeof WithParamsIdRoute
  '/pets': typeof PetsIndexRoute
  '/with-search-params': typeof WithSearchParamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/with-params/$id': typeof WithParamsIdRoute
  '/pets/': typeof PetsIndexRoute
  '/with-search-params/': typeof WithSearchParamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/with-params/$id' | '/pets' | '/with-search-params'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/with-params/$id' | '/pets' | '/with-search-params'
  id: '__root__' | '/' | '/with-params/$id' | '/pets/' | '/with-search-params/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WithParamsIdRoute: typeof WithParamsIdRoute
  PetsIndexRoute: typeof PetsIndexRoute
  WithSearchParamsIndexRoute: typeof WithSearchParamsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/with-search-params/': {
      id: '/with-search-params/'
      path: '/with-search-params'
      fullPath: '/with-search-params'
      preLoaderRoute: typeof WithSearchParamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/': {
      id: '/pets/'
      path: '/pets'
      fullPath: '/pets'
      preLoaderRoute: typeof PetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/with-params/$id': {
      id: '/with-params/$id'
      path: '/with-params/$id'
      fullPath: '/with-params/$id'
      preLoaderRoute: typeof WithParamsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WithParamsIdRoute: WithParamsIdRoute,
  PetsIndexRoute: PetsIndexRoute,
  WithSearchParamsIndexRoute: WithSearchParamsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
