/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as WithSearchParamsIndexImport } from './routes/with-search-params/index'
import { Route as PetsIndexImport } from './routes/pets/index'
import { Route as WithParamsIdImport } from './routes/with-params/$id'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WithSearchParamsIndexRoute = WithSearchParamsIndexImport.update({
  id: '/with-search-params/',
  path: '/with-search-params/',
  getParentRoute: () => rootRoute,
} as any)

const PetsIndexRoute = PetsIndexImport.update({
  id: '/pets/',
  path: '/pets/',
  getParentRoute: () => rootRoute,
} as any)

const WithParamsIdRoute = WithParamsIdImport.update({
  id: '/with-params/$id',
  path: '/with-params/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/with-params/$id': {
      id: '/with-params/$id'
      path: '/with-params/$id'
      fullPath: '/with-params/$id'
      preLoaderRoute: typeof WithParamsIdImport
      parentRoute: typeof rootRoute
    }
    '/pets/': {
      id: '/pets/'
      path: '/pets'
      fullPath: '/pets'
      preLoaderRoute: typeof PetsIndexImport
      parentRoute: typeof rootRoute
    }
    '/with-search-params/': {
      id: '/with-search-params/'
      path: '/with-search-params'
      fullPath: '/with-search-params'
      preLoaderRoute: typeof WithSearchParamsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/with-params/$id': typeof WithParamsIdRoute
  '/pets': typeof PetsIndexRoute
  '/with-search-params': typeof WithSearchParamsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/with-params/$id': typeof WithParamsIdRoute
  '/pets': typeof PetsIndexRoute
  '/with-search-params': typeof WithSearchParamsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/with-params/$id': typeof WithParamsIdRoute
  '/pets/': typeof PetsIndexRoute
  '/with-search-params/': typeof WithSearchParamsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/with-params/$id' | '/pets' | '/with-search-params'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/with-params/$id' | '/pets' | '/with-search-params'
  id: '__root__' | '/' | '/with-params/$id' | '/pets/' | '/with-search-params/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WithParamsIdRoute: typeof WithParamsIdRoute
  PetsIndexRoute: typeof PetsIndexRoute
  WithSearchParamsIndexRoute: typeof WithSearchParamsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WithParamsIdRoute: WithParamsIdRoute,
  PetsIndexRoute: PetsIndexRoute,
  WithSearchParamsIndexRoute: WithSearchParamsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/with-params/$id",
        "/pets/",
        "/with-search-params/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/with-params/$id": {
      "filePath": "with-params/$id.tsx"
    },
    "/pets/": {
      "filePath": "pets/index.tsx"
    },
    "/with-search-params/": {
      "filePath": "with-search-params/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
